import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Button, Container } from "reactstrap";
import Header from "../components/Header";
import Image from "next/image";
import Footer from "@/components/Footer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Container className="text-center mw-100 p-0">
          <Image
            src="/assets/Cupcake-main-banner.jpg"
            alt="Banner Principal"
            width={1920}
            height={1080}
            className="main-banner"
          />
          <h1 className="mt-5 display-1">O melhor cupcake do mundo!!!</h1>
          <div className="d-flex align-items-center justify-content-center">
            <div className="w-50">
              <p className="text-home">
                Na nossa loja de cupcakes, cada bolinho é feito com amor e os
                ingredientes mais frescos para trazer um sorriso ao seu rosto.
                Desde os clássicos até os sabores mais ousados, nossos cupcakes
                são perfeitos para qualquer ocasião, seja um aniversário, uma
                reunião especial ou simplesmente um momento de indulgência.
                Nosso compromisso é com a qualidade e a satisfação do cliente.
                Cada cupcake é cuidadosamente decorado, combinando beleza e
                sabor para criar uma experiência inesquecível. Além disso,
                oferecemos opções personalizadas para atender aos seus desejos
                específicos, garantindo que cada pedido seja tão único quanto
                você. Explore nosso site e descubra a variedade de sabores e
                opções que temos a oferecer. Deixe-se levar pelo aroma e a
                textura de nossos cupcakes fresquinhos, prontos para transformar
                qualquer dia em um dia especial. Porque na nossa loja, a
                felicidade é servida em formas de papel.
              </p>
              <Link href="/products">
                <Button className="px-4 pb-2 btn-addcart">
                  Conheça nossos produtos!
                </Button>
              </Link>
            </div>
            <Image
              src="/assets/Cupcake-sobre.jpg"
              alt="Vários cupcakes"
              width={650}
              height={650}
              className="w-50"
            />
          </div>
        </Container>
      </main>

      <Footer />
    </>
  );
};

export default Home;
